---
title: "LPWC Applied to a Long Time Series"
author: "John Steill"
#date: "5/27/2018"
urlcolor: blue
output: pdf_document
---

## The application of LPWC to a long time series. 

Lag Penalized Weighted Correlation for Time Series Clustering (LPWC) is
described both in a [paper on bioRxiv](https://doi.org/10.1101/292615) and its
[github repository](https://github.com/gitter-lab/LPWC).

Briefly the algorithm accomplishes two main tasks: it chooses optimal lags to 
offset sequences, and build an all-to-all distance matrix which can then be made
available for various hierarchical clustering. For this 
application, I am using data from Thomson Lab Submission 391: "Characterize the 
progression from ES to mesendoderm to definitive endoderm (4 days) and to SOX2+ 
foregut endoderm (8 days). This submission is a robotic hourly time course 
collection over the first 4 days of differentiation (total 12 days). 
Each time point is collected at triplicates."

For this data set the sequences are the normalized expression values for each 
gene. 





<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- #install.packages("LPWC", repos = "http://cran.us.r-project.org") -->
<!-- library(ggplot2) -->
<!-- library(here) -->
<!-- source('LPWC_Analysis_Utilities.R') -->
<!-- if (file.exists('wkspace_lo.RData')){ -->
<!--     load(file='wkspace_lo.RData') -->
<!-- } -->
<!-- # Maybe cluster genes first then correlate.  -->
<!-- # Maybe just describe the application  -->
<!-- # > z = data.frame(x=1, y= tpm_lo$solution$lags) -->
<!-- # > p <- ggplot(z, aes(x, y)) -->
<!-- #m> p + geom_violin() -->
<!-- ``` -->
<!-- First we examined raw expected counts -->

<!-- ```{r, include=TRUE} -->
<!-- if (!("solution_lo" %in% ls())){ -->
<!--     dataFile = 'Data/Sub_391_2_pool_22adb_hg19_SOX2_plus__foregut_endoderm__32a860ee85db9ac9/genes.no_mt.ec.tab'  -->
<!--     high_var_data = get_high_var_genes(infile=dataFile, sd_cv_thresh=500) -->
<!--     c(solution_lo,dist_lo,clust_lo)=run_lo_lpwc(dat=high_var_data, timepoints = 0:96) -->
<!-- } -->
<!-- hc = get_h_clust(solution_lo, high_var_data) -->
<!-- plot(hc, cex = .5) -->
<!-- # if (!("sol_tpm_lo" %in% ls())){ -->
<!-- #     dataFile = 'Data/Sub_391_2_pool_22adb_hg19_SOX2_plus__foregut_endoderm__32a860ee85db9ac9/genes.no_mt.tpm.rescale.tab'  -->
<!-- #     high_var_data = get_high_var_genes(infile=dataFile, sd_cv_thresh=500) -->
<!-- #     c(sol_tpm_lo,dist_tpm_lo,clust_tpm_lo)=run_lo_lpwc(dat=high_var_data, timepoints = 0:96) -->
<!-- # } -->
<!-- ``` -->

<!-- ``` {r, include=FALSE} -->
<!-- save.image(file='wkspace_lo.RData') -->
<!-- ``` -->
